battary_node:
  ros__parameters:
    frame_id: 1
    technology: 2
    num_of_consumers: 4
    publish_voltage: True
    design_capacity: 4.2
    number_of_cells: 4
    nominal_voltage: 14.8
    full_charge_voltage: 16.8
    cut_off_voltage: 10
    internal_resistance: 0.11
    current_filter_tau: 1
    polarization_constant: 0.07
    exponential_voltage: 0.7
    exponential_capacity: 3.0
    characteristic_time: 420
    reversible_voltage_temp: 0.05
    arrhenius_rate_polarization: 850
    capacity_temp_coeff: 0.01
    design_temperature: 25
    temperature_response_tau: 0.5
    update_rate: 10.0
    use_nonlinear_model: True
